version: '3.8'

services:
  mongo:
    image: mongo:4.0
    container_name: letschat-mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db

  letschat:
    image: sdelements/lets-chat:latest
    container_name: letschat
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/letschat
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
